### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by afgalvan** [jwar28/Actividad_4#3]
# Bad code
Bad code
https://github.com/jwar28/Actividad_4/blob/2d18ea5876601ce74fc7a78d5af75a738520095b/src/edu/unicesar/taller/cuarto/points/BankTransactions.java#L95
![](https://media0.giphy.com/media/Jq7WUBf71Gju1vTe2A/giphy.gif)

**Comment by jwar28** [comment]
please respect bro
